site_name: VIPickle
repo_name: h4c5/vipickle
repo_url: https://github.com/h4c5/vipickle
edit_uri: edit/main/docs/

# see
theme:
    name: material
    logo: assets/images/logo.svg
    favicon: assets/images/icon.svg
    language: en
    palette:
        - scheme: default
          toggle:
              icon: material/weather-night
              name: Switch to dark mode
          primary: amber

        - scheme: slate
          toggle:
              icon: material/weather-sunny
              name: Switch to dark mode
          primary: amber

nav:
    - Home: index.md
    - Code Reference: reference/

extra:
    alternate:
        - name: French
          link: /fr/
          lang: fr

plugins:
    - content.code.annotate
    - search
    - gen-files:
          scripts:
              - docs/gen_ref_pages.py
    - literate-nav:
          nav_file: SUMMARY.md
    - section-index
    - mkdocstrings

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
