site_name: BlackPickle

# see
theme:
  name: material
  logo: assets/favicon.ico
  favicon: assets/favicon.ico
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal

    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: teal

nav:
  - Home: index.md
  - Code Reference: reference/

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
